---
- name: Add HashiCorp apt Repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Add kubectl repo
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: Add Helm repo
  become: true
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian

- name: Add Ulauncher PPA
  become: true
  apt_repository:
    validate_certs: no
    repo: 'ppa:agornostal/ulauncher'
    state: present

- name: install VS Code repo (apt)
  become: true
  apt_repository:
    repo: “deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main”
    filename: vscode
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present